---
default: &default
  adapter: <%= ENV.fetch("DATABASE_ADAPTER", "mysql") %>
  encoding: <%= ENV.fetch("DATABASE_ENCODING", "utf8") %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", "3306") %>
  pool: <%= ENV.fetch("DATABASE_POOL", "5") %>
  timeout: <%= ENV.fetch("DATABASE_TIMEOUT", "5000") %>

development:
  <<: *default

test:
  <<: *default
  database: mediccm_test

staging:
  <<: *default

production:
  <<: *default
